def load_primary_skills():
    return {
        "machine learning": "ML",
        "ml": "ML",
        "ml models": "ML",
        "ml algorithms": "ML",
        "supervised learning": "ML",
        "unsupervised learning": "ML",
        "reinforcement learning": "ML",

        "deep learning": "DL",
        "dl": "DL",
        "neural networks": "DL",
        "deep neural networks": "DL",
        "cnn": "DL",
        "rnn": "DL",
        "lstm": "DL",
        "transformers": "DL",

        "natural language processing": "NLP",
        "nlp": "NLP",
        "text processing": "NLP",
        "language models": "NLP",

        "computer vision": "CV",
        "cv": "CV",
        "image processing": "CV",
        "object detection": "CV",

        "data science": "Data Science",
        "data analysis": "Data Analysis",
        "data analytics": "Data Analysis",
        "statistics": "Statistics",
        "probability": "Statistics",

        "python": "Python",
        "java": "Java",
        "c": "C",
        "c++": "C++",
        "c#": "C#",
        "javascript": "JavaScript",
        "typescript": "TypeScript",
        "go": "Go",
        "golang": "Go",
        "scala": "Scala",
        "ruby": "Ruby",
        "perl": "Perl",
        "php": "PHP",
        "bash": "Bash",
        "shell scripting": "Shell Scripting",

        "data structures": "Data Structures",
        "algorithms": "Algorithms",
        "object oriented programming": "OOP",
        "oop": "OOP",
        "operating systems": "Operating Systems",
        "os": "Operating Systems",
        "computer networks": "Computer Networks",
        "networking": "Computer Networks",
        "software engineering": "Software Engineering",
        "software architecture": "Software Architecture",
        "system design": "System Design",
        "design patterns": "Design Patterns",
        "sdlc": "SDLC",

        "sql": "SQL",
        "mysql": "MySQL",
        "postgresql": "PostgreSQL",
        "oracle": "Oracle DB",
        "mongodb": "MongoDB",
        "redis": "Redis",
        "cassandra": "Cassandra",
        "hbase": "HBase",
        "elasticsearch": "Elasticsearch",
        "nosql": "NoSQL",

        "rest api": "REST API",
        "restful api": "REST API",
        "api development": "API Development",
        "microservices": "Microservices",
        "service oriented architecture": "SOA",

        "spring": "Spring Framework",
        "spring boot": "Spring Boot",
        "django": "Django",
        "flask": "Flask",
        "fastapi": "FastAPI",
        "node": "Node.js",
        "node.js": "Node.js",
        ".net": ".NET",
        ".net core": ".NET Core",

        "tensorflow": "TensorFlow",
        "pytorch": "PyTorch",
        "keras": "Keras",
        "scikit-learn": "Scikit-learn",
        "sklearn": "Scikit-learn",
        "numpy": "NumPy",
        "pandas": "Pandas",
        "matplotlib": "Matplotlib",
        "spark": "Apache Spark",
        "databricks": "Databricks",

        "cloud computing": "Cloud Computing",
        "aws": "AWS",
        "amazon web services": "AWS",
        "azure": "Azure",
        "gcp": "GCP",
        "google cloud": "GCP",
        "ec2": "AWS EC2",
        "s3": "AWS S3",
        "rds": "AWS RDS",
        "saas": "SaaS",
        "iaas": "IaaS",

        "devops": "DevOps",
        "docker": "Docker",
        "kubernetes": "Kubernetes",
        "ci/cd": "CI/CD",
        "ci cd": "CI/CD",
        "jenkins": "Jenkins",
        "terraform": "Terraform",
        "ansible": "Ansible",
        "chef": "Chef",
        "grafana": "Grafana",
        "prometheus": "Prometheus",

        "linux": "Linux",
        "unix": "Unix",
        "windows": "Windows",
        "embedded linux": "Embedded Linux",
        "rtos": "RTOS",

        "tcp/ip": "TCP/IP",
        "http": "HTTP",
        "dns": "DNS",
        "network security": "Network Security",
        "cybersecurity": "Cybersecurity",
        "information security": "Cybersecurity",
        "cryptography": "Cryptography",
        "security hardening": "Security Hardening",

        "embedded systems": "Embedded Systems",
        "microcontrollers": "Microcontrollers",
        "arm": "ARM Architecture",
        "fpga": "FPGA",
        "verilog": "Verilog",
        "vhdl": "VHDL",
        "soc": "SoC",
        "pcb design": "PCB Design",
        "spi": "SPI",
        "i2c": "I2C",
        "uart": "UART",
    }


def load_secondary_skills():
    return {
        "spring": "Spring",
        "spring boot": "Spring Boot",
        "react": "React",
        "angular": "Angular",
        "vue": "Vue.js",
        "node": "Node.js",
        "node.js": "Node.js",
        "express": "Express.js",
        "html": "HTML",
        "css": "CSS",
        "bootstrap": "Bootstrap",

        "android": "Android",
        "ios": "iOS",
        "kotlin": "Kotlin",
        "swift": "Swift",
        "jetpack compose": "Jetpack Compose",
        "mvvm": "MVVM",

        "git": "Git",
        "github": "GitHub",
        "gitlab": "GitLab",
        "bitbucket": "Bitbucket",
        "jira": "JIRA",

        "jenkins": "Jenkins",
        "grafana": "Grafana",
        "prometheus": "Prometheus",
        "ansible": "Ansible",
        "terraform": "Terraform",
        "excel": "Excel",
        "tableau": "Tableau",
        "power bi": "Power BI",
        "sap": "SAP",

        "spark": "Apache Spark",
        "hadoop": "Hadoop",
        "kafka": "Kafka",

        "wireshark": "Wireshark",
        "nmap": "Nmap",
        "helm": "Helm",
        "istio": "Istio",

        "elasticsearch": "Elasticsearch",
        "cassandra": "Cassandra",
        "postman": "Postman",
        "swagger": "Swagger",
        "openapi": "OpenAPI",
        "unit testing": "Unit Testing",
        "integration testing": "Integration Testing",
        "automation testing": "Automation Testing",
        "tdd": "TDD",

        "gstreamer": "GStreamer",
        "ffmpeg": "FFmpeg",
        "opengl": "OpenGL",
        "yocto": "Yocto",
        "hilt": "Hilt",
    }

